export const AppStrings = {
  APP_NAME: 'MyApp',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  HOME: 'Home',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  NOTIFICATIONS: 'Notifications',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  EMAIL: 'Email',
  SUBMIT: 'Submit',
  CANCEL: 'Cancel',
  OK: 'OK',
  YES: 'Yes',
  NO: 'No',
  LOADING: 'Loading...',
  ERROR: 'Error',
  SUCCESS: 'Success',
  NO_INTERNET: 'No internet connection. Please check your network.',
  SESSION_EXPIRED: 'Your session has expired. Please login again.',
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again.',
  WELCOME: 'Welcome',
  ENTER_USERNAME: 'Enter your username',
  ENTER_PASSWORD: 'Enter your password',
  LOGIN_SUCCESS: 'Login successful!',
  LOGIN_FAILED: 'Login failed. Please try again.',
  CONFIRM_LOGOUT: 'Are you sure you want to logout?',
};

export const ReduxKeys = {
  USER: 'user',
  IS_DARK_THEME: 'isDarkTheme',
  IS_USER_LOGGED_IN: 'isUserLoggedIn',
  USER_NAME: 'userName',
  USER_ID: 'userId',
  USER_EMAIL: 'userEmail',
  USER_PROFILE_IMAGE: 'userProfileImage',
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  FIREBASE_TOKEN: 'firebaseToken',
  IS_PROFILE_VERIFIED: 'isProfileVerified',
  IS_BIOMETRIC_ENABLE: 'isBioMatricEnable',
  IS_NOTIFICATION_ENABLE: 'isNotificationEnable',
};

export default AppStrings;
