// ─── English Strings ─────────────────────────────────────────

export const AppStrings = {
  APP_NAME: 'PM Internship Matchmaker',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  HOME: 'Home',
  DASHBOARD: 'Dashboard',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  NOTIFICATIONS: 'Notifications',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  EMAIL: 'Email',
  SUBMIT: 'Submit',
  CANCEL: 'Cancel',
  OK: 'OK',
  YES: 'Yes',
  NO: 'No',
  LOADING: 'Loading...',
  ERROR: 'Error',
  SUCCESS: 'Success',
  NO_INTERNET: 'No internet connection. Please check your network.',
  SESSION_EXPIRED: 'Your session has expired. Please login again.',
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again.',
  WELCOME: 'Welcome',
  ENTER_MOBILE: 'Enter your 10-digit mobile number',
  ENTER_OTP: 'Enter the 6-digit OTP sent to your mobile',
  REQUEST_OTP: 'Request OTP',
  VERIFY_OTP: 'Verify OTP',
  RESEND_OTP: 'Resend OTP',
  LOGIN_SUCCESS: 'Login successful!',
  LOGIN_FAILED: 'Login failed. Please try again.',
  CONFIRM_LOGOUT: 'Are you sure you want to logout?',
  // ─── Internship-Specific Keys ──────────────────────────────
  AADHAAR_NUMBER: 'Aadhaar Number',
  ENTER_AADHAAR: 'Enter your 12-digit Aadhaar number',
  PAN_NUMBER: 'PAN Number',
  ENTER_PAN: 'Enter your PAN number',
  MOBILE_NUMBER: 'Mobile Number',
  APPLY_NOW: 'Apply Now',
  INTERNSHIP_DETAILS: 'Internship Details',
  APPLICATION_STATUS: 'Application Status',
  EMPLOYER_DASHBOARD: 'Employer Dashboard',
  STIPEND_DETAILS: 'Stipend Details',
  ELIGIBILITY_CHECK: 'Eligibility Check',
  SCHEME_GUIDELINES: 'Scheme Guidelines',
  BROWSE_INTERNSHIPS: 'Browse Internships',
  INTERNSHIPS: 'Internships',
  MY_APPLICATIONS: 'My Applications',
  INVALID_AADHAAR: 'Please enter a valid 12-digit Aadhaar number',
  INVALID_MOBILE: 'Please enter a valid 10-digit mobile number',
  INVALID_PAN: 'Please enter a valid PAN number',
  AGE_RESTRICTION: 'Applicant must be between 21 and 24 years of age',
  COMMUNITY_FORUMS: 'Community Forums',
  RESOURCE_LIBRARY: 'Resource Library',
  CASE_BANK: 'Case Bank',
  MENTORSHIP: '1-on-1 Mentorship',
  AI_CAREER_COACH: 'AI Career Coach',
  LIVE_WORKSHOPS: 'Live Workshops',
};

// ─── Hindi Strings ───────────────────────────────────────────

export const AppStringsHi = {
  APP_NAME: 'पीएम इंटर्नशिप मैचमेकर',
  LOGIN: 'लॉगिन',
  LOGOUT: 'लॉगआउट',
  HOME: 'होम',
  DASHBOARD: 'डैशबोर्ड',
  PROFILE: 'प्रोफ़ाइल',
  SETTINGS: 'सेटिंग्स',
  NOTIFICATIONS: 'सूचनाएं',
  USERNAME: 'उपयोगकर्ता नाम',
  PASSWORD: 'पासवर्ड',
  EMAIL: 'ईमेल',
  SUBMIT: 'सबमिट',
  CANCEL: 'रद्द करें',
  OK: 'ठीक है',
  YES: 'हाँ',
  NO: 'नहीं',
  LOADING: 'लोड हो रहा है...',
  ERROR: 'त्रुटि',
  SUCCESS: 'सफलता',
  NO_INTERNET: 'इंटरनेट कनेक्शन नहीं है। कृपया अपना नेटवर्क जांचें।',
  SESSION_EXPIRED: 'आपका सत्र समाप्त हो गया है। कृपया पुनः लॉगिन करें।',
  SOMETHING_WENT_WRONG: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
  WELCOME: 'स्वागत है',
  ENTER_MOBILE: 'अपना 10 अंकों का मोबाइल नंबर दर्ज करें',
  ENTER_OTP: 'अपने मोबाइल पर भेजा गया 6 अंकों का OTP दर्ज करें',
  REQUEST_OTP: 'OTP का अनुरोध करें',
  VERIFY_OTP: 'OTP सत्यापित करें',
  RESEND_OTP: 'OTP पुनः भेजें',
  LOGIN_SUCCESS: 'लॉगिन सफल!',
  LOGIN_FAILED: 'लॉगिन विफल। कृपया पुनः प्रयास करें।',
  CONFIRM_LOGOUT: 'क्या आप लॉगआउट करना चाहते हैं?',
  AADHAAR_NUMBER: 'आधार नंबर',
  ENTER_AADHAAR: 'अपना 12 अंकों का आधार नंबर दर्ज करें',
  PAN_NUMBER: 'पैन नंबर',
  ENTER_PAN: 'अपना पैन नंबर दर्ज करें',
  MOBILE_NUMBER: 'मोबाइल नंबर',
  APPLY_NOW: 'अभी आवेदन करें',
  INTERNSHIP_DETAILS: 'इंटर्नशिप विवरण',
  APPLICATION_STATUS: 'आवेदन की स्थिति',
  EMPLOYER_DASHBOARD: 'नियोक्ता डैशबोर्ड',
  STIPEND_DETAILS: 'वजीफा विवरण',
  ELIGIBILITY_CHECK: 'पात्रता जांच',
  SCHEME_GUIDELINES: 'योजना दिशानिर्देश',
  BROWSE_INTERNSHIPS: 'इंटर्नशिप ब्राउज़ करें',
  INTERNSHIPS: 'इंटर्नशिप',
  MY_APPLICATIONS: 'मेरे आवेदन',
  INVALID_AADHAAR: 'कृपया एक वैध 12 अंकों का आधार नंबर दर्ज करें',
  INVALID_MOBILE: 'कृपया एक वैध 10 अंकों का मोबाइल नंबर दर्ज करें',
  INVALID_PAN: 'कृपया एक वैध पैन नंबर दर्ज करें',
  AGE_RESTRICTION: 'आवेदक की आयु 21 से 24 वर्ष के बीच होनी चाहिए',
  COMMUNITY_FORUMS: 'सामुदायिक मंच',
  RESOURCE_LIBRARY: 'संसाधन पुस्तकालय',
  CASE_BANK: 'केस बैंक',
  MENTORSHIP: '1-on-1 मेंटरशिप',
  AI_CAREER_COACH: 'AI करियर कोच',
  LIVE_WORKSHOPS: 'लाइव वर्कशॉप',
};

// ─── Locale Resolver ─────────────────────────────────────────

export const getStrings = (locale = 'en') => {
  return locale === 'hi' ? AppStringsHi : AppStrings;
};

// ─── Redux Keys ──────────────────────────────────────────────

export const ReduxKeys = {
  USER: 'user',
  IS_DARK_THEME: 'isDarkTheme',
  IS_USER_LOGGED_IN: 'isUserLoggedIn',
  USER_NAME: 'userName',
  USER_ID: 'userId',
  USER_EMAIL: 'userEmail',
  USER_MOBILE: 'userMobile',
  USER_PROFILE_IMAGE: 'userProfileImage',
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  FIREBASE_TOKEN: 'firebaseToken',
  IS_PROFILE_VERIFIED: 'isProfileVerified',
  IS_BIOMETRIC_ENABLE: 'isBioMatricEnable',
  IS_NOTIFICATION_ENABLE: 'isNotificationEnable',
  AADHAAR_VERIFIED: 'aadhaarVerified',
  USER_ROLE: 'userRole',
  LOCALE: 'locale',
};

export default AppStrings;
